#!/bin/bash
# Proper header for a Bash script

DIRTY_DIR=./
# Variables are better; will allow for easy future modification

cd $DIRTY_DIR

sed -i -e 's/\r$//' $1

echo $1 "cleaned"

exit # The proper method of exiting from a script.