#!/bin/bash
# The 'mydate' command gives the date, but is polite about it

script_name=`basename $0`   
days=$(date +%j)
secs=$(date +$s)

echo "*** $script_name ***"

echo "The number of days since the year's beginning is "$(date +%j)
# Needs a leading '+' to invoke formatting.
# %j gives day of year

echo "The number of seconds elapsed since 01/01/1970 is "$(date +%s)
# %s yields number of seconds since "UNIX epoch" began,
#+ but how is this useful?

prefix=temp     # No spaces in assignment allowed
suffix=$(date +%s)  # The "+%s" option to 'date' is GNU-specific
filename=$prefix.$suffix
echo "Temporary filename = $filename"
# Great for creating unique and random temp filenames, even better than using $$.

exit 0
