#!/bin/bash

# For loop
echo -n "Values of \"a\" in the loop are: " # -n specifies not to print new line
for a in 7 8 9 11
do
    echo -n "$a "
done

echo    # will print a new line

# Read statement
echo -n "Enter \"a\" "
read a
echo -n "The value of \"a\" is now $a."

echo

# simple variable assignment
a=23
echo $a
b=$a
echo $b

# command substitution
a=`echo Hello!`     # assigns result of 'echo' command to 'a'. Notice use of backtick `
echo $a
a=`ls -l`
echo $a
echo
echo "$a"   # The quoted variable preserves whitespace

exit 0
